# Generated by Django 4.2 on 2024-09-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofileapp', '0002_experience_education_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='project_images/', verbose_name='Image 1')),
                ('image2', models.ImageField(upload_to='project_images/', verbose_name='Image 2')),
                ('github_link', models.URLField(blank=True)),
            ],
        ),
    ]
